---
debug:
  addr: 0.0.0.0:8390
  token:
  pprof: false

ldap:
  addr: 0.0.0.0:10389
  data: data.json

tracing:
  enabled: false
  type: jaeger
  endpoint: localhost:6831
  collector: http://localhost:14268/api/traces
  service: devldap

asset:
  path:

...
